/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'hero-slides': HeroSlide;
    history: History;
    whoweare: Whoweare;
    'our-values': OurValue;
    footer: Footer;
    'product-categories': ProductCategory;
    products: Product;
    vigilance: Vigilance;
    'contact-submissions': ContactSubmission;
    'pharmavigilance-submissions': PharmavigilanceSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    history: HistorySelect<false> | HistorySelect<true>;
    whoweare: WhoweareSelect<false> | WhoweareSelect<true>;
    'our-values': OurValuesSelect<false> | OurValuesSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    vigilance: VigilanceSelect<false> | VigilanceSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'pharmavigilance-submissions': PharmavigilanceSubmissionsSelect<false> | PharmavigilanceSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {
    'home-settings': HomeSetting;
    'nav-settings': NavSetting;
    'contact-settings': ContactSetting;
    'about-settings': AboutSetting;
    'pharmavigilance-settings': PharmavigilanceSetting;
  };
  globalsSelect: {
    'home-settings': HomeSettingsSelect<false> | HomeSettingsSelect<true>;
    'nav-settings': NavSettingsSelect<false> | NavSettingsSelect<true>;
    'contact-settings': ContactSettingsSelect<false> | ContactSettingsSelect<true>;
    'about-settings': AboutSettingsSelect<false> | AboutSettingsSelect<true>;
    'pharmavigilance-settings': PharmavigilanceSettingsSelect<false> | PharmavigilanceSettingsSelect<true>;
  };
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  _order?: string | null;
  tag?: string | null;
  title: string;
  subtitle?: string | null;
  image: number | Media;
  ctaText?: string | null;
  ctaLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "history".
 */
export interface History {
  id: number;
  title: string;
  description: string;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whoweare".
 */
export interface Whoweare {
  id: number;
  title: string;
  description: string;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Esta colección controla la sección "Nuestros Valores" del Home. Crea un único documento.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-values".
 */
export interface OurValue {
  id: number;
  /**
   * Ej: "Nuestros Valores" — se muestra como heading principal.
   */
  sectionTitle: string;
  /**
   * Imagen lateral con forma de hoja. Opcional pero recomendada.
   */
  image?: (number | null) | Media;
  /**
   * Cada valor tiene un ícono, un título y sus puntos descriptivos.
   */
  values?:
    | {
        icon:
          | 'heart'
          | 'lightbulb'
          | 'trending-up'
          | 'shield'
          | 'star'
          | 'users'
          | 'award'
          | 'target'
          | 'leaf'
          | 'hand-heart'
          | 'brain'
          | 'book-open'
          | 'rocket'
          | 'circle-check';
        title: string;
        /**
         * Cada punto tiene una etiqueta en negrita y un texto descriptivo.
         */
        points?:
          | {
              label: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contenido del pie de página. Solo debe existir UN documento.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Texto breve bajo el logo (máx. 2 líneas recomendado).
   */
  brandDescription: string;
  /**
   * Botones de redes sociales (LinkedIn, Instagram, etc.).
   */
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Hasta 2 columnas de links (Compañía, Soporte, etc.).
   */
  linkColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  contactTitle: string;
  /**
   * Cada salto de línea se muestra como un párrafo separado.
   */
  address?: string | null;
  contactEmail?: string | null;
  /**
   * El símbolo © se agrega automáticamente al inicio.
   */
  copyrightText: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * Ej: cardiovascular, respiratorio, dolor
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * Ej: cardiotrex-10mg (sin espacios, en minúsculas)
   */
  slug: string;
  category: number | ProductCategory;
  /**
   * Frase breve que aparece en la tarjeta. Máx. 80 caracteres.
   */
  tagline?: string | null;
  activeIngredient?: string | null;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Ej: Tabletas 10mg × 20, Jarabe 120 mL
   */
  presentations?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  status?: ('active' | 'inactive') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contenido de la página de Farmacovigilancia. Solo debe existir UN documento.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vigilance".
 */
export interface Vigilance {
  id: number;
  pageTitle?: string | null;
  /**
   * Texto pequeño en verde sobre el título.
   */
  heroEyebrow?: string | null;
  heroTitulo?: string | null;
  heroSubtitulo?: string | null;
  infoEyebrow?: string | null;
  infoTitulo?: string | null;
  /**
   * Aparecen de 2 en 2, con navegación entre pares.
   */
  infoBlocks?:
    | {
        title: string;
        style?: ('bullet' | 'numbered') | null;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Formularios de contacto recibidos desde el sitio web.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  nombres: string;
  apellidos: string;
  telefono: string;
  correo: string;
  formaContacto: 'whatsapp' | 'telefono' | 'correo';
  mensaje?: string | null;
  aceptaPoliticas: boolean;
  estado?: ('nuevo' | 'seguimiento' | 'contactado' | 'cerrado') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reportes de efectos adversos recibidos desde el sitio web.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pharmavigilance-submissions".
 */
export interface PharmavigilanceSubmission {
  id: number;
  nombreRemitente?: string | null;
  correoRemitente?: string | null;
  /**
   * Todas las respuestas enviadas desde el formulario web.
   */
  respuestas?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  estado?: ('nuevo' | 'revision' | 'procesado' | 'cerrado') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'hero-slides';
        value: number | HeroSlide;
      } | null)
    | ({
        relationTo: 'history';
        value: number | History;
      } | null)
    | ({
        relationTo: 'whoweare';
        value: number | Whoweare;
      } | null)
    | ({
        relationTo: 'our-values';
        value: number | OurValue;
      } | null)
    | ({
        relationTo: 'footer';
        value: number | Footer;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'vigilance';
        value: number | Vigilance;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'pharmavigilance-submissions';
        value: number | PharmavigilanceSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  _order?: T;
  tag?: T;
  title?: T;
  subtitle?: T;
  image?: T;
  ctaText?: T;
  ctaLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "history_select".
 */
export interface HistorySelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whoweare_select".
 */
export interface WhoweareSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-values_select".
 */
export interface OurValuesSelect<T extends boolean = true> {
  sectionTitle?: T;
  image?: T;
  values?:
    | T
    | {
        icon?: T;
        title?: T;
        points?:
          | T
          | {
              label?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandDescription?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  linkColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  contactTitle?: T;
  address?: T;
  contactEmail?: T;
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  category?: T;
  tagline?: T;
  activeIngredient?: T;
  description?: T;
  image?: T;
  presentations?:
    | T
    | {
        label?: T;
        id?: T;
      };
  featured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vigilance_select".
 */
export interface VigilanceSelect<T extends boolean = true> {
  pageTitle?: T;
  heroEyebrow?: T;
  heroTitulo?: T;
  heroSubtitulo?: T;
  infoEyebrow?: T;
  infoTitulo?: T;
  infoBlocks?:
    | T
    | {
        title?: T;
        style?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  nombres?: T;
  apellidos?: T;
  telefono?: T;
  correo?: T;
  formaContacto?: T;
  mensaje?: T;
  aceptaPoliticas?: T;
  estado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pharmavigilance-submissions_select".
 */
export interface PharmavigilanceSubmissionsSelect<T extends boolean = true> {
  nombreRemitente?: T;
  correoRemitente?: T;
  respuestas?: T;
  estado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Home page content. Each section in its corresponding tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-settings".
 */
export interface HomeSetting {
  id: number;
  /**
   * Drag to reorder. Each slide is a full screen.
   */
  heroSlides?:
    | {
        /**
         * Ej: INNOVACIÓN FARMACÉUTICA
         */
        tag?: string | null;
        title: string;
        subtitle?: string | null;
        image: number | Media;
        /**
         * Ej: Ver productos
         */
        ctaText?: string | null;
        /**
         * Ej: /products
         */
        ctaLink?: string | null;
        id?: string | null;
      }[]
    | null;
  histTitle: string;
  /**
   * Separa párrafos con saltos de línea.
   */
  histDescription: string;
  histImage?: (number | null) | Media;
  whoTitle: string;
  /**
   * Separa párrafos con saltos de línea.
   */
  whoDescription: string;
  whoImage?: (number | null) | Media;
  valSectionTitle: string;
  /**
   * Imagen con forma de hoja (opcional)
   */
  valImage?: (number | null) | Media;
  /**
   * Cada valor tiene un ícono, un título y sus puntos descriptivos.
   */
  values?:
    | {
        icon:
          | 'heart'
          | 'lightbulb'
          | 'trending-up'
          | 'shield'
          | 'star'
          | 'users'
          | 'award'
          | 'target'
          | 'leaf'
          | 'hand-heart'
          | 'brain'
          | 'book-open'
          | 'rocket'
          | 'circle-check';
        title: string;
        points?:
          | {
              label: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Navigation menu items and contact button text. Enable or disable each item without deleting it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-settings".
 */
export interface NavSetting {
  id: number;
  /**
   * Deactivate an item to hide it without deleting it.
   */
  items?:
    | {
        etiqueta: string;
        /**
         * Ej: /about · /products
         */
        ruta: string;
        /**
         * Activa o desactiva por idioma de forma independiente.
         */
        activo?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ej: Contáctenos · Hablar con nosotros · Contact Us
   */
  ctaLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Texts, WhatsApp data, contact options and privacy policy for the Contact modal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings".
 */
export interface ContactSetting {
  id: number;
  /**
   * Ej: 51957255145  →  wa.me/51957255145
   */
  whatsappNumero: string;
  whatsappDisponible?: boolean | null;
  whatsappNombreAgente?: string | null;
  whatsappRolAgente?: string | null;
  /**
   * El usuario puede editarlo antes de enviar
   */
  whatsappMensaje?: string | null;
  waTitulo?: string | null;
  waSubtitulo?: string | null;
  waBtnTexto?: string | null;
  /**
   * Enable or disable options. Order here is the order in the form.
   */
  opcionesContacto?:
    | {
        valor: 'whatsapp' | 'telefono' | 'correo';
        etiqueta: string;
        /**
         * message-circle · phone · mail · send
         */
        icono: string;
        activo?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ej: "Contáctanos"
   */
  formEyebrow?: string | null;
  formTitulo?: string | null;
  formBtnEnviar?: string | null;
  formTituloExito?: string | null;
  formSubtituloExito?: string | null;
  /**
   * Use {{link}} as placeholder where the clickable link will appear.
   */
  politicaTexto?: string | null;
  politicaLinkTexto?: string | null;
  /**
   * Ej: /politica-de-privacidad
   */
  politicaLinkUrl?: string | null;
  /**
   * Se muestra en el panel izquierdo del modal
   */
  telefono?: string | null;
  email?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the "About Us" page. Edit each section in its corresponding tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-settings".
 */
export interface AboutSetting {
  id: number;
  /**
   * Ej: "Nosotros" · Aparece en verde sobre el título principal
   */
  heroEyebrow?: string | null;
  /**
   * Título grande de la sección
   */
  heroTitulo?: string | null;
  /**
   * Texto secundario en color apagado, debajo del título
   */
  heroSubtitulo?: string | null;
  heroDescripcion?: string | null;
  /**
   * Se mostrará en el elemento decorativo de la portada
   */
  heroImagen?: (number | null) | Media;
  heroStats?:
    | {
        /**
         * Ej: 15+
         */
        valor: string;
        /**
         * Ej: Años de experiencia
         */
        etiqueta: string;
        id?: string | null;
      }[]
    | null;
  misionTitulo?: string | null;
  /**
   * target · heart · shield · leaf · star · award · hand-heart · lightbulb
   */
  misionIcono?: string | null;
  misionTexto?: string | null;
  visionTitulo?: string | null;
  /**
   * eye · trending-up · globe · rocket · book-open · brain
   */
  visionIcono?: string | null;
  visionTexto?: string | null;
  /**
   * Ej: "Nuestro Equipo"
   */
  equipoEyebrow?: string | null;
  equipoTitulo?: string | null;
  /**
   * Each group appears as a tab on the site. Add members within each group.
   */
  equipoGrupos?:
    | {
        nombre: string;
        miembros?:
          | {
              nombre: string;
              cargo?: string | null;
              foto?: (number | null) | Media;
              /**
               * https://linkedin.com/in/nombre
               */
              linkedin?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ej: "Aliados Estratégicos"
   */
  aliadosEyebrow?: string | null;
  aliadosTitulo?: string | null;
  aliadosSubtitulo?: string | null;
  aliados?:
    | {
        nombre: string;
        /**
         * Ej: https://laboratorioalpha.com
         */
        url?: string | null;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Define las secciones y campos del formulario de reporte de efectos adversos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pharmavigilance-settings".
 */
export interface PharmavigilanceSetting {
  id: number;
  titulo?: string | null;
  subtitulo?: string | null;
  descripcion?: string | null;
  /**
   * Cada sección agrupa campos relacionados.
   */
  secciones?:
    | {
        titulo: string;
        campos?:
          | {
              /**
               * Sin espacios. Ej: nombreCompleto
               */
              clave: string;
              etiqueta: string;
              tipo: 'text' | 'email' | 'number' | 'date' | 'textarea' | 'radio' | 'select';
              ancho?: ('full' | 'half' | 'third') | null;
              requerido?: boolean | null;
              activo?: boolean | null;
              placeholder?: string | null;
              opciones?:
                | {
                    valor: string;
                    etiqueta: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  emailContacto?: string | null;
  telefonoContacto?: string | null;
  direccionContacto?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-settings_select".
 */
export interface HomeSettingsSelect<T extends boolean = true> {
  heroSlides?:
    | T
    | {
        tag?: T;
        title?: T;
        subtitle?: T;
        image?: T;
        ctaText?: T;
        ctaLink?: T;
        id?: T;
      };
  histTitle?: T;
  histDescription?: T;
  histImage?: T;
  whoTitle?: T;
  whoDescription?: T;
  whoImage?: T;
  valSectionTitle?: T;
  valImage?: T;
  values?:
    | T
    | {
        icon?: T;
        title?: T;
        points?:
          | T
          | {
              label?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-settings_select".
 */
export interface NavSettingsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        etiqueta?: T;
        ruta?: T;
        activo?: T;
        id?: T;
      };
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings_select".
 */
export interface ContactSettingsSelect<T extends boolean = true> {
  whatsappNumero?: T;
  whatsappDisponible?: T;
  whatsappNombreAgente?: T;
  whatsappRolAgente?: T;
  whatsappMensaje?: T;
  waTitulo?: T;
  waSubtitulo?: T;
  waBtnTexto?: T;
  opcionesContacto?:
    | T
    | {
        valor?: T;
        etiqueta?: T;
        icono?: T;
        activo?: T;
        id?: T;
      };
  formEyebrow?: T;
  formTitulo?: T;
  formBtnEnviar?: T;
  formTituloExito?: T;
  formSubtituloExito?: T;
  politicaTexto?: T;
  politicaLinkTexto?: T;
  politicaLinkUrl?: T;
  telefono?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-settings_select".
 */
export interface AboutSettingsSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitulo?: T;
  heroSubtitulo?: T;
  heroDescripcion?: T;
  heroImagen?: T;
  heroStats?:
    | T
    | {
        valor?: T;
        etiqueta?: T;
        id?: T;
      };
  misionTitulo?: T;
  misionIcono?: T;
  misionTexto?: T;
  visionTitulo?: T;
  visionIcono?: T;
  visionTexto?: T;
  equipoEyebrow?: T;
  equipoTitulo?: T;
  equipoGrupos?:
    | T
    | {
        nombre?: T;
        miembros?:
          | T
          | {
              nombre?: T;
              cargo?: T;
              foto?: T;
              linkedin?: T;
              id?: T;
            };
        id?: T;
      };
  aliadosEyebrow?: T;
  aliadosTitulo?: T;
  aliadosSubtitulo?: T;
  aliados?:
    | T
    | {
        nombre?: T;
        url?: T;
        logo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pharmavigilance-settings_select".
 */
export interface PharmavigilanceSettingsSelect<T extends boolean = true> {
  titulo?: T;
  subtitulo?: T;
  descripcion?: T;
  secciones?:
    | T
    | {
        titulo?: T;
        campos?:
          | T
          | {
              clave?: T;
              etiqueta?: T;
              tipo?: T;
              ancho?: T;
              requerido?: T;
              activo?: T;
              placeholder?: T;
              opciones?:
                | T
                | {
                    valor?: T;
                    etiqueta?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  emailContacto?: T;
  telefonoContacto?: T;
  direccionContacto?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}